version: '2'

services:
  mysql-service:
    image: "mysql:5.7"
    container_name: mysql-service
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=kuxopZpfq6:X
    volumes:
    - "/Users/didi/mysql:/var/lib/mysql"
    - "/Users/didi/apollo_mysql_scripts:/opt/mysql/scripts"

  apollo-configservice:
    image: "apollo-configservice"
    container_name: apollo-configservice
    depends_on:
    - mysql-service
    ports:
    - "8080:8080"
    volumes:
    - "/opt/logs/configservice:/opt/logs"

  apollo-adminservice:
    image: "apollo-adminservice"
    container_name: apollo-adminservice
    depends_on:
    - mysql-service
    - apollo-configservice
    ports:
    - "8090:8090"
    volumes:
    - "/opt/logs/adminservice:/opt/logs"
    environment:
    - eureka.service.url=http://apollo-configservice:8080/eureka/

  apollo-portal:
    image: "apollo-portal"
    container_name: apollo-portal
    depends_on:
    - mysql-service
    - apollo-configservice
    ports:
    - "8070:8070"
    volumes:
    - "/opt/logs/portal:/opt/logs"